### PR TITLE
Modified startup script and server

### PR DESCRIPTION
**Pull request by bheesham**
- The server's configuration can now be set in `etc/server_{prod, devel}.yml`.
- The installation script installs redis.

### CODE REVIEW

File: etc/server_devel.yml [hunk 1]
```diff
@@ -0,0 +1,4 @@
+server_port: 25414
+req_timeout: 3000
+
+# vim: ft=yaml
```
Comment (psimonyi) [inline etc/server_devel.yml:6]: In modelines, I kind of prefer the full versions of commands (i.e. `filetype=yaml`), though I'd compromise to get this all on one line (especially since `ft` is a common enough option; more esoteric options really need to be readable).
It's probably a good idea to grab the standard vim modeline from the wiki, too.

File: src/server/index.js [hunk 2]
```diff
@@ -7,14 +7,18 @@
...
 var connect = require('connect');
 var cors = require('cors');
 
 /******************************************************************************
 * Configuration                                                               *
 ******************************************************************************/
-var serverPort = 20193;
-var requestTimeout = 3000; // ms
+
+var server_config = require(process.env.SERVER_CONF);
```
Comment (psimonyi) [inline src/server/index.js]: Woah! You just _execute_ the YAML file?! Isn't there something like YAML.parse?

File: src/server/package.json [hunk 3]
```diff
@@ -28,7 +28,8 @@
     "redis":            ">=0.8.2",
     "connect":          ">=2.7.3",
     "cors":             ">=0.0.5",
-    "proxy-middleware": ">=0.3.1"
+    "proxy-middleware": ">=0.3.1",
+		"js-yaml": 					">=2.0.3"
```
Comment (psimonyi) [inline src/server/package.json]: Spacing

File: bin/install_server.sh [hunk 4]
```diff
@@ -14,6 +14,9 @@ ROOT_DIR=`pwd`
 ######################################################################
 # Configuration
 ######################################################################
+
+CLIENT_TARGET_DIR=~/webapps/cr_front
```
Comment (psimonyi) [inline bin/install_server.sh]: I don't like the idea of deploying to a home directory -- especially a hard-coded path.

File: bin/install_server.sh [hunk 5]
```diff
@@ -22,16 +25,42 @@ NODE_VERSION=0.10.2
...
+tar -xf $REDIS_F.tar.gz -C $BIN_DIR/
+rm $REDIS_F.tar.gz
+mv -f $REDIS_F redis
+cd $BIN_DIR/redis 
+
+echo Compiling redis
+make
+
+echo Copying client files into the specified directory 
+cp -R $ROOT_DIR/src/client/* $CLIENT_TARGET_DIR/
```
Comment (psimonyi) [inline bin/install_server.sh]: It seems strange to be dealing with client files in `install_server.sh`. The file description at the top makes no mention of this.

File: bin/start.sh [hunk 6]
```diff
@@ -18,7 +18,7 @@ NODE_BIN=$ROOT_DIR/bin/exe/node/bin
 NPM=$NODE_BIN/npm
 NODE=$NODE_BIN/node
 
-DB=redis-server
+DB=$ROOT_DIR/bin/exe/redis/src/redis-server
```
Comment (psimonyi) [inline bin/start.sh]: `bin/exe/redis/src` what?

File: bin/start.sh [hunk 7]
```diff
@@ -62,7 +65,24 @@ ln -s -f $DB_LOG.$TIME.log $DB_LINK
...
+fi
+
+$NODE $INDEX_SCRIPT &> $SERVER_LOG.$TIME.log &
+
 echo $! > $SERVER_PID
 ln -s -f $SERVER_LOG.$TIME.log $SERVER_LINK
+
+
+
+
```
Comment (psimonyi) [inline bin/start.sh]: Extra blank lines at EOF

**Comment by psimonyi** [comment]
It seems this still installs node, npm and redis even in development mode.

File: bin/install_server.sh [hunk 8]
```diff
@@ -22,16 +25,42 @@ NODE_VERSION=0.10.2
...
 rm $NODE_F.tar.gz
-mv $NODE_F node
+mv -f $NODE_F node
+
+echo - complete!
+
+echo Installing component: redis
+
+echo - downloading...
+wget -q http://redis.googlecode.com/files/$REDIS_F.tar.gz
```
Comment (cdelahousse) [inline bin/install_server.sh]: Shouldn't we host a reliable version as we've done with our front end dependencies?

Comment (psimonyi) [inline bin/install_server.sh]: I thought we were hosting things only when we couldn't find a good download link.

File: bin/install_server.sh (hunk 4 above)
Comment (spratt) [inline bin/install_server.sh]: Is there an obvious better way to do this?

**Comment by bheesham** [comment]
@psimonyi , If you already have the things install, why install them again?
You should be using `start.sh`

``` bash
alias vim=sudo yum install vim && vim
```

File: bin/install_server.sh (hunk 8 above)
Comment (spratt) [inline bin/install_server.sh]: I only hosted things when the only option was over https or there was no real download link.

**Comment by spratt** [comment]
Outstanding issues for @bheesham:
- spacing in  `src/server/package.json`
- installing to a home directory in `bin/install_server.sh`
- add copying of client files to description of `bin/install_server.sh`

**Comment by bheesham** [comment]
[Currently it does copy client files.](https://github.com/bheesham/Steamed-Pears/blob/master/bin/install_server.sh#L66)

**Comment by spratt** [comment]
The problem is that there is no mention of copying client files in the description in the header of `bin/install_server.sh`

**Comment by bheesham** [comment]
Ah, okay.

Also, for installation of the server to a home directory.
When you install this as root, and run it as another person, would that user not be able to find it? Because root's home dir is different.

**Comment by spratt** [comment]
Why not reply directly to the comments on the lines of code?  It's easier to understand when there's context to what you're saying.

**Comment by bheesham** [comment]
Because I'm replying directly to your comment.

**Comment by spratt** [comment]
Okay, in general I agree with you.  So why are we installing to a home directory?

File: bin/install_server.sh (hunk 4 above)
Comment (spratt) [inline bin/install_server.sh]: On this line, we install to a home directory.

Comment (spratt) [inline bin/install_server.sh]: Let's talk about this on this line.

Comment (psimonyi) [inline bin/install_server.sh]: I think the Right Thing To Do is have a good default like `/srv/code_review` or maybe `/var/www/code_review` and check an environment variable or command-line parameter for a user-specified value. (Think of installing programs, where the default is usually `/usr/bin` but you can do `./configure --prefix=$HOME/local` instead.) If you go for environment variables, look up Parameter Expansion in `bash(1)`; if you go for command-line parameters, look up getopt.

File: bin/install_server.sh (hunk 5 above)
Comment (psimonyi) [inline bin/install_server.sh]: The main problem is not mentioning this in the description of what this file does, as @spratt says. A minor problem is that the file name `install_server.sh` suggests it's installing the server component, when it really seems to be installing everything.

**Comment by psimonyi** [comment]
This will also fix #123.

**Comment by bheesham** [comment]
Because the user we're installing it as, for sure has the permissions to write files there.
On WebFaction (our production server), that's the only place we're allowed to write.

**Comment by psimonyi** [comment]
Let's discuss the home directory thing on its line.

File: bin/install_server.sh (hunk 4 above)
Comment (psimonyi) [inline bin/install_server.sh]: @bheesham says we can be sure of write access to the home directory.
I think it is better to have a default for when it's your own server, and make it easy to override the default. (And you were worrying about what happens when installing as root before...)

Comment (bheesham) [inline bin/install_server.sh]: Hmm, yeah.
I guess when you run it as root, you'll probably want to put nginx, npm, and redis-server in `/usr/bin``.

As for not having the permissions to put it there, what would you suggest we do? Because changing PATH seems weird, and I feel gross. Because in development, I'd be running this a lot of times.

File: bin/install_server.sh (hunk 5 above)
Comment (bheesham) [inline bin/install_server.sh]: So... do we not want to install everything?

File: bin/start.sh [hunk 9]
```diff
@@ -1,23 +1,35 @@
...
 ######################################################################
 # Configuration
-NPM=npm
-NODE=node
 
-DB=redis-server
+if $PROD; then
+  NPM=$ROOT_DIR/bin/exe/node/bin/npm
+  NODE=$ROOT_DIR/bin/exe/node/bin/node
+  DB=$ROOT_DIR/bin/exe/redis/src/redis-server
```
Comment (psimonyi) [inline bin/start.sh]: These paths are no longer correct, right?

File: .gitignore [hunk 10]
```diff
@@ -1,3 +1,5 @@
+*.swp
```
Comment (psimonyi) [inline .gitignore]: This should probably be `.*.swp` (dotfiles don't normally match `*` in globs). You've committed a swapfile in spite of this, anyway.

Comment (spratt) [inline .gitignore]: Ugh.  Let's get rid of the swapfile.

File: bin/install_server.sh [hunk 11]
```diff
@@ -22,16 +22,61 @@ NODE_VERSION=0.10.2
...
+echo - extracting redis...
+tar -xf redis.tar.gz
+cd $TMP/$REDIS_F 
+
+echo - compiling redis...
+make
+
+echo - installing redis...
+cp $TMP/$REDIS_F/src/redis-server $BIN/redis-server
+cp $TMP/$REDIS_F/src/redis-cli $BIN/redis-cli
```
Comment (psimonyi) [inline bin/install_server.sh]: It would probably be less fragile to do `make PREFIX=$PREFIX install`.

File: bin/install_server.sh [hunk 12]
```diff
@@ -22,16 +22,61 @@ NODE_VERSION=0.10.2
...
+# Redis version
+REDIS_VERSION=2.6.12
+
 ######################################################################
 
+TMP=$PREFIX/tmp
+BIN=$PREFIX/usr/bin
+
+mkdir -p $TMP 2> /dev/null
+mkdir -p $BIN 2> /dev/null
```
Comment (psimonyi) [inline bin/install_server.sh]: We probably want to know about any errors here. `mkdir -p` is silent when the directory exists, at least for me.

File: bin/install_server.sh [hunk 13]
```diff
@@ -22,16 +22,61 @@ NODE_VERSION=0.10.2
 # Can be either 64 or 86
 NODE_ARCH=64
 
+# Redis version
+REDIS_VERSION=2.6.12
+
 ######################################################################
 
+TMP=$PREFIX/tmp
```
Comment (psimonyi) [inline bin/install_server.sh]: `TMP=${TEMP:-${TMP:-/tmp}}` would use the first non-empty path of `$TEMP`, `$TMP`, and `/tmp`. Any of those is probably a good temp directory. In any case, we should probably clean up after ourselves...

File: bin/install_server.sh [hunk 14]
```diff
@@ -22,16 +22,61 @@ NODE_VERSION=0.10.2
...
+BIN=$PREFIX/usr/bin
```
Comment (psimonyi) [inline bin/install_server.sh]: Typically, `PREFIX` values are things like `/usr/local` or `$HOME` or `/usr`; in all cases, I'd expect binaries to go in `$PREFIX/bin`.

Comment (bheesham) [inline bin/install_server.sh]: Well, if it **is** /usr/, that sounds weird. /usr/node ? No thanks?

Comment (psimonyi) [inline bin/install_server.sh]: I'd still kind of like to see a default value for PREFIX, though I won't insist on it. However, the docs should say somewhere that you can use it (and generally tell you how to run this thing).

Comment (psimonyi) [inline bin/install_server.sh]: If `PREFIX` is `/usr`, then `BIN=$PREFIX/bin` would make `/usr/bin/node`, no?

**Comment by psimonyi** [comment]
Blocking on the paths in `start.sh` and the swapfile; the other stuff can be done/discussed later if you want.

**Comment by psimonyi** [comment]
You should also delete `bin/exe/.folder`.

**Comment by psimonyi** [comment]
Perhaps `stop_dev.sh` should be renamed too. Does it work in production mode?

File: bin/install_server.sh (hunk 11 above)
Comment (bheesham) [inline bin/install_server.sh]: Added.

File: bin/install_server.sh (hunk 12 above)
Comment (bheesham) [inline bin/install_server.sh]: Added.

File: bin/install_server.sh (hunk 13 above)
Comment (bheesham) [inline bin/install_server.sh]: Should have noted that I removed this after.

File: bin/install_server.sh (hunk 14 above)
Comment (bheesham) [inline bin/install_server.sh]: Then we create /usr/tmp? Crazy talk.

**Comment by bheesham** [comment]
It should now be mostly non-blocking. I didn't add `TMP=${...`, because I don't have permissions to write to compile in`/tmp`.

**THIS WORKS FOR ME IN PRODUCTION ON WEBFACTION.**

File: bin/install_server.sh (hunk 14 above)
Comment (psimonyi) [inline bin/install_server.sh]: No, you put the temp files in `$TEMP` (or `$TMP`, or `/tmp` if neither is set), and install binaries to `$PREFIX/bin`.

Comment (bheesham) [inline bin/install_server.sh]: I can't compile in the `/tmp` folder. So, there is no installing binaries without compilation.

**Comment by spratt** [comment]
Looks good.  I'm going to pull this down and try it out on my webfaction.

**Comment by spratt** [comment]
Fantastic.  git gives errors pushing to webfaction if I don't have the docs submodule pulled in, but after installing it, it won't upload the docs to webfaction....fine, whatever git.  You suck.

**Comment by bheesham** [comment]
Huh... I never got those errors.

**Comment by spratt** [comment]
Redis fails to build:

```
make[3]: Entering directory `/home/sdp/tmp/redis-2.6.12/deps/jemalloc'
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/jemalloc.o src/jemalloc.c
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/arena.o src/arena.c
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/atomic.o src/atomic.c
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/base.o src/base.c
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/bitmap.o src/bitmap.c
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/chunk.o src/chunk.c
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/chunk_dss.o src/chunk_dss.c
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/chunk_mmap.o src/chunk_mmap.c
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/ckh.o src/ckh.c
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/ctl.o src/ctl.c
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/extent.o src/extent.c
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/hash.o src/hash.c
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/huge.o src/huge.c
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/mb.o src/mb.c
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/mutex.o src/mutex.c
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/prof.o src/prof.c
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/quarantine.o src/quarantine.c
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/rtree.o src/rtree.c
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/stats.o src/stats.c
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/tcache.o src/tcache.c
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/util.o src/util.c
gcc -std=gnu99 -Wall -pipe -g3 -O3 -funroll-loops  -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -o src/tsd.o src/tsd.c
ar crus lib/libjemalloc.a src/jemalloc.o src/arena.o src/atomic.o src/base.o src/bitmap.o src/chunk.o src/chunk_dss.o src/chunk_mmap.o src/ckh.o src/ctl.o src/extent.o src/hash.o src/huge.o src/mb.o src/mutex.o src/prof.o src/quarantine.o src/rtree.o src/stats.o src/tcache.o src/util.o src/tsd.o
make[3]: Leaving directory `/home/sdp/tmp/redis-2.6.12/deps/jemalloc'
make[2]: Leaving directory `/home/sdp/tmp/redis-2.6.12/deps'
    CC adlist.o
    CC ae.o
    CC anet.o
    CC dict.o
    CC redis.o
    CC sds.o
    CC zmalloc.o
    CC lzf_c.o
    CC lzf_d.o
    CC pqsort.o
    CC zipmap.o
    CC sha1.o
    CC ziplist.o
    CC release.o
    CC networking.o
    CC util.o
    CC object.o
    CC db.o
    CC replication.o
    CC rdb.o
    CC t_string.o
    CC t_list.o
    CC t_set.o
    CC t_zset.o
    CC t_hash.o
    CC config.o
    CC aof.o
    CC pubsub.o
    CC multi.o
    CC debug.o
    CC sort.o
    CC intset.o
    CC syncio.o
    CC migrate.o
    CC endianconv.o
    CC slowlog.o
    CC scripting.o
    CC bio.o
    CC rio.o
    CC rand.o
    CC memtest.o
    CC crc64.o
    CC bitops.o
    CC sentinel.o
    LINK redis-server
zmalloc.o: In function `zmalloc_used_memory':
/home/sdp/tmp/redis-2.6.12/src/zmalloc.c:223: undefined reference to `__sync_add_and_fetch_4'
collect2: ld returned 1 exit status
make[1]: *** [redis-server] Error 1
make[1]: Leaving directory `/home/sdp/tmp/redis-2.6.12/src'
make: *** [all] Error 2
cd src && make install
make[1]: Entering directory `/home/sdp/tmp/redis-2.6.12/src'
    LINK redis-server
zmalloc.o: In function `zmalloc_used_memory':
/home/sdp/tmp/redis-2.6.12/src/zmalloc.c:223: undefined reference to `__sync_add_and_fetch_4'
collect2: ld returned 1 exit status
make[1]: *** [redis-server] Error 1
make[1]: Leaving directory `/home/sdp/tmp/redis-2.6.12/src'
make: *** [install] Error 2
- installing redis...
cp: cannot stat `/home/sdp/tmp/redis-2.6.12/src/redis-server': No such file or directory
cp: cannot stat `/home/sdp/tmp/redis-2.6.12/src/redis-cli': No such file or directory
```

File: bin/install_server.sh [hunk 15]
```diff
@@ -22,16 +22,69 @@ NODE_VERSION=0.10.2
...
+
+echo - extracting redis...
+tar -xf redis.tar.gz
+rm redis.tar.gz
+
+cd $TMP/$REDIS_F 
+
+echo - compiling redis...
+make
+make PREFIX=$PREFIX install
```
Comment (spratt) [inline bin/install_server.sh]: I think this should be `PREFIX=$PREFIX make install`

**Comment by spratt** [comment]
The install script works fine on my mac using clang 4.2, but it won't compile on my webfaction host using gcc 4.1.  I have a suspicion that gcc 4.1 is a little out of date.

**Comment by spratt** [comment]
Bhee, I fixed the issues I mentioned above in a pull request to your master branch.

**Comment by spratt** [comment]
[blocking] I can't execute the node binary file that we download using this script.

**Comment by spratt** [comment]
For the record, I found the solution to the redis compile bug from: http://www.eschrade.com/page/undefined-reference-to-__sync_add_and_fetch_4/

**Comment by spratt** [comment]
`uname -m` returns an architecture that my mac's version of gcc doesn't support...and the redis build uses gcc in particular at one stage of its build (as opposed to $CC which would use clang).

**Comment by spratt** [comment]
This now works on the main site.  See: http://review.steamedpears.com

**Comment by spratt** [comment]
@psimonyi you should take a look at this request now.  I think a lot of issues have been fixed.

File: bin/install_server.sh [hunk 16]
```diff
@@ -14,24 +15,80 @@ ROOT_DIR=`pwd`
 ######################################################################
 # Configuration
 ######################################################################
-BIN_DIR=$ROOT_DIR/bin/exe
 
 # A valid node version
-NODE_VERSION=0.10.2
+NODE_VERSION=0.10.4
```
Comment (psimonyi) [inline bin/install_server.sh:20]: The "Requirements" section should probably list this version of Node.

File: bin/install_server.sh [hunk 17]
```diff
@@ -14,24 +15,80 @@ ROOT_DIR=`pwd`
...
 
 # Can be either 64 or 86
 NODE_ARCH=64
 
+# Redis version
+REDIS_VERSION=2.6.12
```
Comment (psimonyi) [inline bin/install_server.sh:26]: Same here. The docs say we've tested with 2.6.10.

File: bin/install_server.sh [hunk 18]
```diff
@@ -14,24 +15,80 @@ ROOT_DIR=`pwd`
...
+wget -O redis.tar.gz -q http://redis.googlecode.com/files/$REDIS_F.tar.gz
+
+echo - extracting redis...
+tar -xf redis.tar.gz
+rm redis.tar.gz
+
+cd $TMP/$REDIS_F 
+
+echo - compiling redis...
+CFLAGS=-march=`uname -m` make
```
Comment (psimonyi) [inline bin/install_server.sh]: Waiting on this thing.

File: bin/build_production_all.sh [hunk 19]
```diff
@@ -13,14 +13,12 @@ CLIENT_SCRIPTS_DIR="$CLIENT_DIR/scripts"
...
-  #Defaults to `production/`
-  TARGET="$PWD/production"
-fi
+# Defaults to `production/`
+TARGET=${TARGET:-$PWD/production}
 
 #Temporary folder for the build
-TARGET_TMP="$TARGET""_tmp"
+TMP=${TEMP:-${TMP:-/tmp}}
+TARGET_TMP=$TMP/cr
```
Comment (psimonyi) [inline bin/build_production_all.sh]: It would be better to use mktemp for this (`mktemp -d --tmpdir="$TMP" codereview-XXXX`). In fact, just `--tmpdir` (no argument) would use `$TMPDIR` if set, and default to `/tmp`.
This can wait for later. [non-blocking]

File: bin/install_server.sh (hunk 18 above)
Comment (spratt) [inline bin/install_server.sh]: By which, Peter means that although it fixes an issue on the server it breaks the build everywhere else.

Comment (psimonyi) [inline bin/install_server.sh]: Right. I think the appropriate thing to do is just call `make` here, and do `export CFLAGS=i686` before running the script, because this seems like a bug caused by an old version of gcc. Other possibilities, since Webfaction is currently our primary deployment target, are: have a script `webfaction_hack.bash` that does that, or try to detect the version of GCC (but that's not exactly easy).

Comment (spratt) [inline bin/install_server.sh]: I like the export CFLAGS fix.  We can document the issue and the resolution.

**Comment by spratt** [comment]
This pull request can't be automatically merged...

**Comment by bheesham** [comment]
It can now.

**Comment by spratt** [comment]
Builds nicely on my mac.  Fails on the server without -march=i686.  Now testing with -march=i686.

**Comment by spratt** [comment]
Builds successfully on server.  I'll do one last review then merge.

File: bin/install_server.sh (hunk 16 above)
Comment (spratt) [inline bin/install_server.sh:20]: Fixed.

File: bin/install_server.sh (hunk 17 above)
Comment (spratt) [inline bin/install_server.sh:26]: Fixed.
